version: 2
jobs:
  build:
    docker:
      # Specify the version you desire here
      - image: circleci/php:7.4-node-browsers
      - image: circleci/mysql:5.7
        environment:
          MYSQL_DATABASE: steak_overflow_dev_test
          MYSQL_ROOT_PASSWORD: root

    steps:
      - checkout

      - run: sudo apt update # PHP CircleCI 2.0 Configuration File# PHP CircleCI 2.0 Configuration File sudo apt install zlib1g-dev libsqlite3-dev
      - run: sudo docker-php-ext-install zip
      - run: sudo docker-php-ext-install zip bcmath pdo_mysql
      - run: sudo apt install default-mysql-client --fix-missing

      # Download and cache dependencies
      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: "Install Dependencies"
          command: composer install -n --prefer-dist

      - run:
          name: "Assets Install and Build"
          command: yarn install && yarn build

      - run:
          name: "Migration"
          command: php bin/console doctrine:migrations:migrate --env=test -q

      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor

      - run:
          name: "Coding Standards"
          command: composer coding-standards

      - run:
          name: "Run tests"
          command: composer test
